### np.array 함수로 생성하기

In [1]:
import numpy as np

x = np.array([1, 2, 3, 4])
print(x)

y = np.array([[2, 3, 4], [1, 2, 5]])
print(y)

[1 2 3 4]
[[2 3 4]
 [1 2 5]]


In [2]:
print(type(y))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1, 10)

array([1, 3, 5, 7, 9])

In [5]:
np.arange(1, 10, 2)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

np.arange(5, 101, 5)

In [8]:
### np.ones, np.zeros로 생성하기

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.ones((4, 5))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [11]:
np.ones((2, 3, 4)) #3행 4열짜리가 2개

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

np.zeros((2, 4, 8))

In [14]:
### np.empty, np.full로 생성하기

array([[7.77549655e-312, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 2.65129316e-032, 2.85223970e-056,
        4.17936428e-062],
       [1.46338903e-047, 6.94111260e+169, 9.42181487e-047,
        6.23129500e-038]])

In [15]:
np.empty((3, 4))

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

np.full((3, 4), 7)

In [17]:
### np.eye로 생성하기
* 단위 행렬 생성

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

np.eye(3)

In [19]:
### np.linspace로 생성하기

array([ 1. ,  5.5, 10. ])

In [20]:
np.linspace(1, 10, 3)

array([ 1.,  4.,  7., 10.])

np.linspace(1, 10, 4)

In [21]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [25]:
### reshape 함수 활용
* ndarray의 형태, 차원을 바꾸기 위해 사용

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
x = np.arange(1, 16)
print(x)

x.shape #튜플

x.reshape(3, 5)