### 학습목표
* random 서브모듈 함수를 통해 ndarray 생성하기

In [2]:
import numpy as np

### rand 함수
* 0, 1 사이의 분포로 랜덤한 ndarray 생성

In [4]:
np.random.rand(2, 3)

array([[0.83618428, 0.96801626, 0.63894719],
       [0.30535308, 0.59141505, 0.62383633]])

### randn 함수
* n: normal distribution(정규분포)
* 정규분포로 샘플링된 랜덤 ndarray 생성

In [5]:
np.random.randn(3, 4, 2)

array([[[-0.70688061, -0.47313997],
        [-0.49355189, -0.44011627],
        [-0.47551835,  1.56872091],
        [ 0.11820676,  0.10904262]],

       [[-0.60494441, -0.99154413],
        [-1.76109517, -0.73967819],
        [-1.10892108, -1.38231442],
        [ 0.60706467,  0.07626948]],

       [[ 0.35204458, -0.87800098],
        [-1.36500425,  2.13840612],
        [ 0.75782441,  1.66184063],
        [ 0.85666481, -0.87892385]]])

### randint 함수
* 특정 정수 사이에서 랜덤하게 샘플링

In [8]:
np.random.randint(1, 100, size=(3, 5))

array([[41, 94, 80, 99,  9],
       [19, 56, 37, 55, 82],
       [ 8, 44, 86, 50, 89]])

### seed 함수
* 랜덤한 값을 동일하게 다시 생성하고자 할 때 사용

In [17]:
np.random.seed(100)

In [18]:
np.random.randn(3, 4)

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349]])

### choice
* 주어진 1차원 ndarray로 부터 랜덤으로 샘플링
* 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [20]:
np.random.choice(100, size=(3, 4))

array([[83,  4, 91, 59],
       [67,  7, 49, 47],
       [65, 61, 14, 55]])

In [21]:
x = np.array([1, 2, 3, 1.5, 2.6, 4.9])
np.random.choice(x, size=(2, 2), replace=False)

array([[2.6, 4.9],
       [2. , 3. ]])

### 확률분포에 따른 ndarray 생성
* uniform
* normal 등등

In [22]:
np.random.uniform(1.0, 3.0, size=(4, 5))

array([[2.59132502, 1.03050994, 2.19768675, 2.20760908, 1.21029537],
       [1.76388689, 1.07295211, 2.78082313, 2.96184171, 1.11988398],
       [2.78109189, 2.153803  , 2.48495938, 2.26036787, 2.16368438],
       [1.04087826, 1.42005316, 2.08936976, 2.53823034, 1.50139046]])

In [24]:
np.random.normal(size=(3, 4)) #same
np.random.randn(3, 4) #same

array([[-0.07961125, -0.88973148, -0.88179839,  0.01863895],
       [ 0.23784462,  0.01354855, -1.6355294 , -1.04420988],
       [ 0.61303888,  0.73620521,  1.02692144, -1.43219061]])