In [1]:
import numpy as np

### numpy documentation
+ numpy 공식 문서 링크
+ numpy에서 제공되는 함수 등에 대한 문서

In [5]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.16958732 0.2007817  0.293035   0.30955282 0.25833692]
 [0.3570275  0.12805945 0.35577654 0.08672069 0.03040318]
 [0.26621309 0.78261433 0.81189227 0.7918163  0.06565497]]


### 연산 함수
+  add, subtract, multiply, divide

In [6]:
np.add(x, y)

array([[ 0.16958732,  1.2007817 ,  2.293035  ,  3.30955282,  4.25833692],
       [ 5.3570275 ,  6.12805945,  7.35577654,  8.08672069,  9.03040318],
       [10.26621309, 11.78261433, 12.81189227, 13.7918163 , 14.06565497]])

In [7]:
np.divide(x, y)

array([[  0.        ,   4.9805335 ,   6.82512328,   9.69139941,
         15.48365576],
       [ 14.00452331,  46.85323797,  19.67527159,  92.25019255,
        296.02162645],
       [ 37.56389266,  14.05545434,  14.78028611,  16.41794939,
        213.23594407]])

### 통계 함수
+ 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [8]:
print(y)

[[0.16958732 0.2007817  0.293035   0.30955282 0.25833692]
 [0.3570275  0.12805945 0.35577654 0.08672069 0.03040318]
 [0.26621309 0.78261433 0.81189227 0.7918163  0.06565497]]


In [9]:
print(np.mean(y))
print(y.mean())

0.32716480668585085
0.32716480668585085


In [11]:
np.max(y)

0.8118922671829198

In [12]:
np.var(y), np.median(y), np.std(y)

(0.06430988957771211, 0.2662130916865657, 0.2535939462560416)

### 집계 함수
+ 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [13]:
y

array([[0.16958732, 0.2007817 , 0.293035  , 0.30955282, 0.25833692],
       [0.3570275 , 0.12805945, 0.35577654, 0.08672069, 0.03040318],
       [0.26621309, 0.78261433, 0.81189227, 0.7918163 , 0.06565497]])

In [14]:
np.sum(y)

4.907472100287762

In [15]:
np.cumsum(y)

array([0.16958732, 0.37036903, 0.66340403, 0.97295685, 1.23129377,
       1.58832127, 1.71638073, 2.07215726, 2.15887795, 2.18928113,
       2.45549423, 3.23810856, 4.05000082, 4.84181713, 4.9074721 ])

### any, all 함수
+ any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
+ all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [16]:
z = np.random.randn(10)
print(z)

[-0.25353385  0.34792394 -0.74043122  1.15210919  0.01579407  0.02495761
 -1.32857484 -1.77177812 -0.2807079   0.57302282]


In [17]:
np.any(z>0)

True

In [18]:
z>0

array([False,  True, False,  True,  True,  True, False, False, False,
        True])

In [19]:
np.all(z>0)

False

### where 함수
+ 조건에 따라 선별적으로 값을 선택 가능
+ ex) 음수인 경우는 0, 나머지는 그대로 값을 쓰는 경우

In [20]:
z = np.random.randn(10)
print(z)

[-0.78207743 -1.25308232  1.04097763  0.7215224   0.86274672  0.08322639
 -2.10486843  0.78636303  1.00942083  0.208191  ]


In [21]:
np.where(z>0, z, 0)

array([0.        , 0.        , 1.04097763, 0.7215224 , 0.86274672,
       0.08322639, 0.        , 0.78636303, 1.00942083, 0.208191  ])