In [1]:
import numpy as np

### broadcasting
+ Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
+ 연산되는 두 ndarray가 다른 Shape을 갖는 경우 broadcasting(Shape을 맞춤) 후 진행

+ Shape이 같은 경우의 연산

In [2]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.96359434 0.92050896 0.17118907 0.43347651 0.60878215]
 [0.4889141  0.2375206  0.25420513 0.99740583 0.21098434]
 [0.31088984 0.76409224 0.45645339 0.18442551 0.09534392]]


In [3]:
x + y

array([[ 0.96359434,  1.92050896,  2.17118907,  3.43347651,  4.60878215],
       [ 5.4889141 ,  6.2375206 ,  7.25420513,  8.99740583,  9.21098434],
       [10.31088984, 11.76409224, 12.45645339, 13.18442551, 14.09534392]])

+ Scalar(상수)와의 연산

In [4]:
x + 2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

+ Shape이 다른 경우 연산

In [9]:
a = np.arange(12).reshape(4, 3)
b = np.arange(100, 103)
c = np.arange(1000, 1004)

print(a)
print(b)
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[100 101 102]
[1000 1001 1002 1003]


In [6]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [8]:
a + c

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 