### Boolean indexing
+ ndarray 인덱싱 시, bool 리스트를 전달하여 True인 경우에만 필터링
+ 브로드캐스팅을 활용하여 ndarray로부터 bool list 얻기
    + 예) 짝수인 경우만 찾아보기

In [1]:
import numpy as np

In [3]:
x = np.random.randint(1, 100, size=10)
print(x)

[32 96 76 73 36 72 88 40 70 24]


In [5]:
even_mask = x % 2 == 0

+ bool 리스트를 인덱스로 전달

In [6]:
x[even_mask]

array([32, 96, 76, 36, 72, 88, 40, 70, 24])

In [7]:
x > 30

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

### 다중조건 사용하기
+ 파이썬 논리 연산자인 and, or, not 키워드 사용 불가
+ & - AND
+ | - OR

In [8]:
x % 2 == 0
x < 30

x[(x % 2 == 0) & (x < 30)]

array([24])

In [9]:
x < 30
x > 50

x[(x<30) | (x>50)]

array([96, 76, 73, 72, 88, 70, 24])

### 예제) 2019년 7월 서울 평균기온 데이터
+ 평균기온이 25도를 넘는 날수는?
+ 평균기온이 25도를 넘는 날의 평균 기온은?

In [ ]:
temp = nd.array()

len(temp)

len(temp[temp > 25])

np.sum(temp > 25.0)

np.mean(temp[temp > 25.0])