## 학습목표
### 1. linalg 서브모듈 함수 활용하여 선형대수 연산하기

In [1]:
import numpy as np

* np.linalg.inv
   + 역행렬을 구할 때 사용
   + 모든 차원의 값이 같아야 함

In [5]:
x = np.random.rand(3, 3, 3)
print(x)

np.matmul(x, np.linalg.inv(x))
x @ np.linalg.inv(x)

[[[0.60697238 0.59483988 0.92378527]
  [0.71214054 0.11005475 0.20416973]
  [0.46597842 0.78549735 0.34036458]]

 [[0.12739794 0.36444835 0.54822546]
  [0.97924028 0.06875629 0.78739949]
  [0.09280709 0.6783646  0.36991993]]

 [[0.81982639 0.56475419 0.14016987]
  [0.81275545 0.09709291 0.9143747 ]
  [0.13986944 0.25172173 0.26883885]]]


array([[[ 1.00000000e+00,  7.57586217e-17,  9.21869495e-17],
        [ 1.31259849e-18,  1.00000000e+00, -1.10885678e-17],
        [-7.66383242e-17, -1.07606209e-16,  1.00000000e+00]],

       [[ 1.00000000e+00, -3.90024232e-17, -2.00820624e-16],
        [-2.20190977e-16,  1.00000000e+00, -8.09705652e-17],
        [-1.72969672e-16, -1.41867978e-17,  1.00000000e+00]],

       [[ 1.00000000e+00,  6.31554351e-17, -1.63318434e-17],
        [ 9.47107382e-18,  1.00000000e+00,  9.06670644e-18],
        [ 2.02481077e-17, -5.41368494e-18,  1.00000000e+00]]])

* np.linalg.solve
   + Ax = B 형태의 선형대수식 솔루션을 제공

In [8]:
A = np.array([[1, 1], [2, 4]])
B = np.array([25, 64])

x = np.linalg.solve(A, B)

print(x)

np.allclose(A@x, B)

[18.  7.]


True